### PR TITLE
feat(CacheModel): add a CacheModel mixin

### PR DESCRIPTION
**Pull request by kenjiqq**
My attempt at a cache model mixin based on the discussions in #27.
Thoughts?

I haven't quite figured out a good way to get the last test to pass `should remove destroyed record from collections`, without looking through all the items in the cache and everything cached for each of those items.

### CODE REVIEW

**Comment by jpulec** [comment]
@kenborge This PR is quite old and out of date. Do you still have any interest in getting it included?

**Comment by kenborge** [comment]
No not really went with another library years ago. Will close it.

**Comment by joseglego** [comment]
@kenborge can you tell me which library do you use?

**Comment by kenjiqq** [comment]
@joseglego We use http://www.js-data.io/ as it was built around resource caching

**Pull request closed without merging**
